export type PlaceData = {
  시설명: string;
  카테고리1: string;
  카테고리2: string;
  카테고리3: string;
  "시도 명칭": string;
  "시군구 명칭": string;
  법정읍면동명칭: string;
  "리 명칭": string;
  번지: string;
  "도로명 이름": string;
  "건물 번호": string;
  위도: string;
  경도: string;
  우편번호: number;
  도로명주소: string;
  지번주소: string;
  전화번호: string;
  홈페이지: string;
  휴무일: string;
  운영시간: string;
  "주차 가능여부": string;
  "입장(이용료)가격 정보": string;
  "반려동물 동반 가능정보": string;
  "반려동물 전용 정보": string;
  "입장 가능 동물 크기": string;
  "반려동물 제한사항": string;
  "장소(실내) 여부": string;
  "장소(실외)여부": string;
  "기본 정보_장소설명": string;
  "애견 동반 추가 요금": string;
  최종작성일: string;
};
